### ISSUE TITLE
customCSSObj is undefined

### ISSUE THREAD

**Issue by CWBudde** [blizz31/customcssinjector#1]
The console always reports: `customCSSObj is undefined`, which is not a big deal, but I prefer my console to be clean.

Eventually, an additional check would help to avoid this.

**Comment by LiteApplication** [comment]
The branch has been merged, but the extension is not up to date on Firefox Add-ons.

**Comment by blizz31** [comment]
Sorry for delay. New version has been submitted on Firefox Add-ons (in review)

**Comment by blizz31** [comment]
Issue addressed however new issue has prevented latest version from being approved (see issues)
