### ISSUE TITLE
Having multiple css rules for multiple sites

### ISSUE THREAD

**Issue by ramast** [blizz31/customcssinjector#3]
Suppose I want to provide custom css rules one domain (say example.com) and completely different rules for a different domain (example2.com). How do I get to do that?

Right now I can define the rules and specify whether I want it globally or for specific domain/url and click save.

I was expecting after clicking save that I'd get list of rules but instead it remains in the same edit css form

**Comment by blizz31** [comment]
After you click Save the CSS which you have specified in the text area will be applied to the DOM in a <style> tag at the very bottom of the <HTML>.

**Comment by blizz31** [comment]
(html element)
