### ISSUE TITLE
Contributing, code of conduct, and license files

### ISSUE THREAD

**Issue by laignelet16** [blizz31/customcssinjector#5]
Hello, 

I am interested in contributing to your project, however, I noticed that there is no contributing, code of conduct or license files. These files can help people know that they can contribute to the repo. I would love to contribute by adding these in the repo and continue adding features to the extension. Thank you!

**Comment by blizz31** [comment]
Hey,

Thanks for your email. I've added some default license and code of conduct.
Hope this helps.

Kind regards,
Bryce

**Comment by laignelet16** [comment]
Thank you!
